<a href="https://colab.research.google.com/github/umaretiya/iN_Assignment/blob/main/iNeuron_Python_Programming_Basic_Assignment_01_to_08.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Programming_Assingment-01#

In [ ]:
#Write a Python program to print "Hello Python"?
print('Hello Python')

Hello Python


In [ ]:
#Write a Python program to do arithmetical operations addition and division.?
print(20 + 10 ==30)
print(20/10 == 2)
print(20+10)
print(30-20)
print(20/10)

True
True
30
10
2.0


In [ ]:
#Write a Python program to find the area of a triangle?
heightFromBase= h=6
base = b=5
areaOfTriangle  = h*b/2
print(areaOfTriangle)

15.0


In [ ]:
#Write a Python program to swap two variables?
a,b = 5,9
c=a
a=b
b=c
a,b


(9, 5)

In [ ]:
#Write a Python program to generate a random number?
import random
from random import randint

random.randint(50,100)

96

#Programming_Assingment-02#

In [ ]:
#Write a Python program to convert kilometers to miles?
# 1 KM = 0.621371 mile
km = 2
mile  = km*0.621371
mile 

1.242742

In [ ]:
#Write a Python program to convert Celsius to Fahrenheit?
#(0°C × 9/5) + 32 = 32°F
celseus  = 39
Fahrenheit = celseus*(9/5) +32
Fahrenheit

102.2

In [ ]:
#Write a Python program to display calendar?
import datetime
import calendar
yy = 2021
print(calendar.calendar(yy))

                                  2021

      January                   February                   March
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
             1  2  3       1  2  3  4  5  6  7       1  2  3  4  5  6  7
 4  5  6  7  8  9 10       8  9 10 11 12 13 14       8  9 10 11 12 13 14
11 12 13 14 15 16 17      15 16 17 18 19 20 21      15 16 17 18 19 20 21
18 19 20 21 22 23 24      22 23 24 25 26 27 28      22 23 24 25 26 27 28
25 26 27 28 29 30 31                                29 30 31

       April                      May                       June
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
          1  2  3  4                      1  2          1  2  3  4  5  6
 5  6  7  8  9 10 11       3  4  5  6  7  8  9       7  8  9 10 11 12 13
12 13 14 15 16 17 18      10 11 12 13 14 15 16      14 15 16 17 18 19 20
19 20 21 22 23 24 25      17 18 19 20 21 22 23      21 22 23 24 25 26 27
26 27 28 29 30            24 25 26 27 

In [ ]:
#Write a Python program to solve quadratic equation?
import math
# quadratic equation is ax^2+bx+c=0
# (-b±√(b²-4ac))/(2a) 
a,b,c = 3,2,4

x1 = (-b+((b**2 - 4*a*c)**(1/2)))/(2*a)
x2 = (-b-((b**2 - 4*a*c)**(1/2)))/(2*a)
x1,x2 #is soluttions 

((-0.33333333333333326+1.1055415967851332j),
 (-0.3333333333333334-1.1055415967851332j))

In [ ]:
#Write a Python program to swap two variables without temp variable?
a,b =40,60


b=a+b #b=30
a=b-a # a= 20
b=b-a # b=10

a,b

(60, 40)

#Programming_Assingment-03#

In [ ]:
"""Write a Python Program to Print all Prime Numbers in an Interval of 1-10000?"""

for Number in range (1, 10000):
  count = 0
  for i in range(2, (Number//2 +1)):
    if Number % i == 0:
      count = count +1
      break
  if count == 0 and Number != 1:
    print(Number, end=',')


2,3,5,7,11,13,17,19,23,29,31,37,41,43,47,53,59,61,67,71,73,79,83,89,97,101,103,107,109,113,127,131,137,139,149,151,157,163,167,173,179,181,191,193,197,199,211,223,227,229,233,239,241,251,257,263,269,271,277,281,283,293,307,311,313,317,331,337,347,349,353,359,367,373,379,383,389,397,401,409,419,421,431,433,439,443,449,457,461,463,467,479,487,491,499,503,509,521,523,541,547,557,563,569,571,577,587,593,599,601,607,613,617,619,631,641,643,647,653,659,661,673,677,683,691,701,709,719,727,733,739,743,751,757,761,769,773,787,797,809,811,821,823,827,829,839,853,857,859,863,877,881,883,887,907,911,919,929,937,941,947,953,967,971,977,983,991,997,1009,1013,1019,1021,1031,1033,1039,1049,1051,1061,1063,1069,1087,1091,1093,1097,1103,1109,1117,1123,1129,1151,1153,1163,1171,1181,1187,1193,1201,1213,1217,1223,1229,1231,1237,1249,1259,1277,1279,1283,1289,1291,1297,1301,1303,1307,1319,1321,1327,1361,1367,1373,1381,1399,1409,1423,1427,1429,1433,1439,1447,1451,1453,1459,1471,1481,1483,1487,1489,1493,1499,15

In [ ]:
#Write a Python Program to Check if a Number is Positive, Negative or Zero?

number = int(input('Check if a Number is Positive, Negative or Zero?: '))

if number > 0:
  print(f"{number} is postive")
elif number < 0:
  print(f"{number} is negative")
else:
  print(f"{number} is Zero")

Check if a Number is Positive, Negative or Zero?: 0
0 is Zero


In [ ]:
#Write a Python Program to Check if a Number is Odd or Even?
number = int(input('Check if a Number is Odd or Even?: '))

if number%2 == 0:
  print(f"{number} is even number")
else:
  print(f"{number} is odd number")

Check if a Number is Odd or Even?: 20
20 is even number


In [ ]:
#Write a Python Program to Check Leap Year?
year = int(input('Leap Year or not?: '))

if ((year % 400 == 0) or (year % 4 == 0) and (year % 100 !=0)): 
  print(f"{year} is a leap year")
else:
  print(f"{year} is not a leap year")

Leap Year or not?: 2000
2000 is a leap year


In [ ]:
#Write a Python Program to Check Prime Number?
number = int(input('Enter a number: '))
count = 0

for i in range(2, (number//2 +1)):
  if number % i == 0:
    count += count +1
    break
if count == 0 and number != 0:
  print(f"{number} is a prime number")
else:
  print(f"{number} is a not prime number")

Enter a number: 4
4 is a not prime number


In [ ]:
for Number in range (1, 101):
    count = 0
    for i in range(2, (Number//2 + 1)):
        if(Number % i == 0):
            count = count + 1
            break

    if (count == 0 and Number != 1):
        print(" %d" %Number, end = '  ')

 2   3   5   7   11   13   17   19   23   29   31   37   41   43   47   53   59   61   67   71   73   79   83   89   97  

In [ ]:
True or True and False

True

True

#Programming_Assingment-04#

1. Write a Python Program to Find the Factorial of a Number?

In [ ]:
number = int(input('enter a number: '))
factorial = 1
for i in range(0,number):
  factorial *=number
  number -=1
print(factorial)


enter a number: 10
3628800


2. Write a Python Program to Display the multiplication Table?

In [ ]:
table_name =int(input('enter a tabel name:'))
for i in range(0,11):
  print(f"{table_name} X {i}  = {table_name*i}")


3. Write a Python Program to Print the Fibonacci sequence?

In [ ]:
def fib02(number):
  a = 0
  b = 1
  for i in range(1,number+1):    
    yield a
    a,b = b,a+b
for i in fib02(10):
  print(i)

4. Write a Python Program to Check Armstrong Number?

In [ ]:
num = int(input('enter a number'))
sum = 0

temp = num

while temp > 0:
    digit = temp % 10
    sum += digit**3
    temp //= 10

if num == sum:
    print(f"{num} is a armstrong number")
else:
    print(f"{num} is not a armstrong number")


enter a number407
407 is a armstrong number


5. Write a Python Program to Find Armstrong Number in an Interval?

In [ ]:
l = []
for number in range(10,100000):
    order = len(str(number))    
    sum = 0
    temp = number
    while temp > 0:
        digit = temp % 10
        sum += digit**order
        temp //= 10

    if number == sum:    
        l.append(number)
print(f"Armstrong number :{l} ")

Armstrong number :[153, 370, 371, 407, 1634, 8208, 9474, 54748, 92727, 93084] 


6. Write a Python Program to Find the Sum of Natural Numbers?

In [ ]:
natural_number = int(input('Enter a number: '))
sum = 0

while natural_number > 0:
  sum = sum + natural_number
  natural_number -= 1
print(sum)

Enter a number: 5
15



#Programming_Assingment-05#

1. Write a Python Program to Find LCM?

In [ ]:
# Find the LCM of two numbers

n1 = int(input('Number one : '))
n2 = int(input('Number second : '))

if n1 > n2:
  lcm = n1
else:
  lcm = n2

while True:
  if lcm % n1 == 0 and lcm % n2 == 0:
    break
  else:
    lcm +=1

print(f'LCM of {n1} and {n2} is {lcm}')

Number one : 84
Number second : 24
LCM of 84 and 24 is 168


2. Write a Python Program to Find HCF?

In [ ]:
#Find the HCF of two number
num1 = int(input('Enter a number one : '))
num2 = int(input('Enter a number two : '))

if num1 > num2:
  hcf = num1
else:
  hcf = num2

while True:
  if num1 % hcf == 0 and num2 % hcf == 0:
    break
  else:
    hcf -= 1
print(f'HCF of {num1} and {num2} is {hcf}')

Enter a number one : 84
Enter a number two : 24
HCF of 84 and 24 is 12


3. Write a Python Program to Convert Decimal to Binary, Octal and Hexadecimal?

In [ ]:
#Coonvert decimal to binary,octal and hexadecimal

def convertor(n):
  print('Binary is {:b}, Octal is {:o} ,and Hexadecimal is {:x}'.format(n,n,n))
  

convertor(16)

Binary is 10000, Octal is 20 ,and Hexadecimal is 10


4. Write a Python Program To Find ASCII value of a character?

In [ ]:
#function ti find ASCII Value(integer) of character

char = 'A'
ch2 = 'a'

print(f'{ord(char)},{ord(ch2)}')
print(f'{chr(97)},{chr(65)}')

65,97
a,A


5. Write a Python Program to Make a Simple Calculator with 4 basic mathematical operations?

In [ ]:
# Write a fuction to make simple calculator

n1= float(input('Enter a Number1: '))

print('What do you want to perform calculation  +,-,*,/ : ')
flag = True
while flag:    
    operation = input()
    if operation == '+' or operation == '-' or operation =='/' or operation == '*':
        cal = operation
        flag = False
    else:
        print('Enter a proper operation')
        

n2 = float(input('Enter a Number2: '))

def add():
    return n1 + n2

def substract():
    return n1 - n2

def multiply():
    return n1 * n2

def division():
    return n1 / n2

calculs = {'+':add(),'-':substract(),'*':multiply(),'/':division() }
final = calculs[cal]

def result(final):
    print(f'this is a final result: {final}')
    return final

result(final)

Enter a Number1: 80
What do you want to perform calculation  +,-,*,/ : 
/
Enter a Number2: 8
this is a final result: 10.0


10.0

#Programming_Assingment-06#

1. Write a Python Program to Display Fibonacci Sequence Using Recursion?

In [ ]:
def fibonacci(n):
  a = 0
  b = 1
  for i in range(0,n+1):
    yield a
    a,b = b,a+b
n = int(input('How many fibonacci wants: '))
for i in fibonacci(n):
  print(i,end=",")

How many fibonacci wants: 10
0,1,1,2,3,5,8,13,21,34,55,

2. Write a Python Program to Find Factorial of Number Using Recursion?

In [ ]:
def factorial():
  n =  int(input('Enter a number for find factorial:! '))

  x = 1
  for i in range(1,n+1):
    x *= i
  return x

factorial()

Enter a number for find factorial:! 7


5040

3. Write a Python Program to calculate your Body Mass Index?

$BMI = kg/m2 $

In [ ]:
weight = float(input('Enter a weight: '))
height = float(input('Enter a Height: '))
bmi = round(weight/(height*height),2)

print(f'BMI is {bmi} kg/meter square')

Enter a weight: 80
Enter a Height: 1.7
BMI is 27.68 kg/meter square


4. Write a Python Program to calculate the natural logarithm of any number?

In [ ]:
import math
n = int(input('wants to find loge value of: '))
print('Natural Logarithm is:',math.log(n))

wants to find loge value of: 20
Natural Logarithm is: 2.995732273553991


5. Write a Python Program for cube sum of first n natural numbers?

In [ ]:
n = int(input('Natural number up to: '))
sum = 0
for i in range(1,n+1):
  sum += i**3
print(f"Sum of from 1 to {n} number's cube is {sum}")

Natural number up to: 3
Sum of from 1 to 3 number's cube is 36


#Programming_Assingment-07#

1. Write a Python Program to find sum of array?

In [ ]:
from array import *
# Programm to find sum of two array

a = array('i', [3,5,6,7])
b = array('i', [10,20,30,40])

def find_sum(x,y):
  #check type of input
  if type(x) and type(y) == array :
    sum_array = x + y
    return sum_array

  
find_sum(a,b)

array('i', [3, 5, 6, 7, 10, 20, 30, 40])

In [ ]:
# Programm to find sum of two array

bd = array('f', [10.5, 25.5])

def array_sum(arr):
  if type(arr) == array :
    sum = 0
    for i in arr:
      sum = sum +i
  return sum

array_sum(bd)

36.0

2. Write a Python Program to find largest element in an array?

In [ ]:
import numpy as np
# Find the largest element in the array

a1 = np.linspace(0,10,5)
max(a1)


10.0

3. Write a Python Program for array rotation?

In [63]:
from array import *
# Array rotation as per our reuirements

a2 = array('i', [10,20,30,50,40,60])

def rotate(arr,d,n):
  arr[:] = arr[d:n] + arr[0:d]
  return arr

rotate(a2,2,len(a2))

array('i', [30, 50, 40, 60, 10, 20])

4. Write a Python Program to Split the array and add the first part to the end?

In [71]:
arr1 = array('i',[])

for i in range(2,24,2):
  arr1.append(i)

def split(array,d,n):
  '''d = postion of index where to split
  n = length of array '''
  array = array[d:len(array)] + array[0:d]
  return array

split(arr1,6,len(arr1))

array('i', [14, 16, 18, 20, 22, 2, 4, 6, 8, 10, 12])

5. Write a Python Program to check if given array is Monotonic?

In [81]:
# Check given matrice is Monotonic or not:
from array import *

def isMonotonic(a):
  return all(a[i] <= a[i+1] for i in range(len(a)-1)) or all(a[i] >= a[i+1] for i in range(len(a)-1))

a = [4,5,6,9]
isMonotonic(a)

True

#Programming_Assingment-08#

1. Write a Python Program to Add Two Matrices?

In [98]:
from numpy import *
# Two matrices sum 

Matrice_1 = matrix('2 4 5; 5 6 7')
Matrice_2 = matrix('9 8 7;10 1 1')
print(Matrice_1)
print(Matrice_2)
sum = Matrice_1 + Matrice_2

print('Sum of two Matrices is : ')
print(sum)

[[2 4 5]
 [5 6 7]]
[[ 9  8  7]
 [10  1  1]]
Sum of two Matrices is : 
[[11 12 12]
 [15  7  8]]



2. Write a Python Program to Multiply Two Matrices?

In [107]:
from numpy import *
# Two matrices multiplication
# r1 and r2 are row of Matrices rexpectively
# c1 and c2 are column of matrices respectively

r1 ,c2 = 2 , 2
r2, c1 = 3 , 3

x = reshape(matrix('2 4 5 5 6 7'),(r1, c1))
y = reshape(matrix('9 8 7 10 7 1'),(r2, c2))

Mult_Matrices = x * y
print(Mult_Matrices)

[[ 81  61]
 [136 107]]


3. Write a Python Program to Transpose a Matrix?


In [111]:
# Transpose a given matreic
from numpy import *

m = matrix('2 3 5; 5 5 3; 8 2 1')
print(m)

n = m.transpose() # transpose matrix function
print(n)

[[2 3 5]
 [5 5 3]
 [8 2 1]]
[[2 5 8]
 [3 5 2]
 [5 3 1]]


4. Write a Python Program to Sort Words in Alphabetic Order?


In [122]:
# Programm to shorting a word in alphabetic order

word = input('enter a word with space : \n')
c = word.split()
c.sort()

type(word)
for i in c:
  print(i, end=' ')

enter a word with space : 
hi i am a kesha umaretiya and i am working with reliance jio at vadodara as an ianl
a am am an and as at hi i i ianl jio kesha reliance umaretiya vadodara with working 

5. Write a Python Program to Remove Punctuation From a String?

In [126]:
# remove punctuation from string 

punc = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

srt = 'hi ! and $ oj) or %'
print(srt)
for i in srt:
  if i in punc:
    srt = srt.replace(i,' ')
print(srt)


hi ! and $ oj) or %
hi   and   oj  or  
